name: Deploy to DigitalOcean
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build and push server
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker build -t $DOCKERHUB_USERNAME/test-deploy-server ./server
          docker push $DOCKERHUB_USERNAME/test-deploy-server

      - name: Build client
        run: |
          cd client
          npm install
          npm run build

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/test-deploy-server
            docker stop server || true
            docker rm server || true
            docker run -d --name server --network td-network -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/test-deploy-server
            rm -rf /var/www/html/*
            mkdir -p /var/www/html
